name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up C++ environment
        uses: aminya/setup-cpp@v1
        with:
          compiler: g++-10

      - name: Install dependencies
        run: sudo apt-get install -y cmake libgtest-dev

      - name: Build and run tests
        run: |
          mkdir build
          cd build
          cmake ..
          cmake --build .
          ctest --output-on-failure

